# Generated by Django 6.0.4 on 2026-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='nlp_hints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='structured_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
