# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_session_nlp_hints_session_structured_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="eventification_detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="eventification_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Olaylaştırma başlamadı"),
                    ("queued", "Olaylaştırma sırada"),
                    ("running", "Olaylaştırılıyor"),
                    ("completed", "Olaylaştırma tamamlandı"),
                    ("failed", "Olaylaştırma hatası"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["eventification_status"], name="diary_sessi_eventif_f9fc31_idx"),
        ),
    ]
