# Generated by Django 6.0.4 on 2026-05-25 21:45

import diary.encryption
from django.db import migrations


ENCRYPTED_FIELDS = [
    "eventification_detail",
    "nlp_hints",
    "processed_text",
    "status_detail",
    "structured_events",
    "transcript",
    "word_timings",
]


def encrypt_existing_session_data(apps, schema_editor):
    Session = apps.get_model("diary", "Session")
    for session in Session.objects.all().iterator():
        session.save(update_fields=ENCRYPTED_FIELDS)
        if session.audio_file:
            storage = session.audio_file.storage
            encrypt_existing = getattr(storage, "encrypt_existing", None)
            if callable(encrypt_existing):
                encrypt_existing(session.audio_file.name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_privacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='eventification_detail',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='nlp_hints',
            field=diary.encryption.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='processed_text',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='status_detail',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='structured_events',
            field=diary.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='session',
            name='transcript',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='session',
            name='word_timings',
            field=diary.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.RunPython(encrypt_existing_session_data, noop_reverse),
    ]
