# Generated by Codex on 2026-05-26

import diary.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0007_alter_encounteredentity_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="mood",
            field=diary.encryption.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="session",
            name="tags",
            field=diary.encryption.EncryptedJSONField(blank=True, default=list),
        ),
    ]
