# Generated by Django 6.0.4 on 2026-04-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERSON', 'Kişi'), ('LOCATION', 'Yer'), ('TIME', 'Zaman'), ('EVENT', 'Olay'), ('ORG', 'Kurum'), ('OTHER', 'Diğer')], max_length=16)),
                ('label', models.CharField(max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('is_unknown', models.BooleanField(default=False)),
                ('time_value', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'label'],
                'indexes': [models.Index(fields=['kind', 'label'], name='diary_node_kind_5cb448_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'label'), name='unique_kind_label')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(max_length=64, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='sessions/%Y/%m/%d/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('recorded_at', models.DateTimeField()),
                ('language', models.CharField(default='tr', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Yüklendi, sırada'), ('transcribing', 'Ses yazıya çevriliyor'), ('parsing', 'Metin analiz ediliyor'), ('review', 'İnceleme bekliyor'), ('completed', 'Tamamlandı'), ('failed', 'Hata')], default='queued', max_length=20)),
                ('status_detail', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('processed_text', models.TextField(blank=True, default='')),
                ('word_timings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['-recorded_at'], name='diary_sessi_recorde_48e6fb_idx'), models.Index(fields=['status'], name='diary_sessi_status_3d0676_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(max_length=200)),
                ('lemma', models.CharField(blank=True, default='', max_length=200)),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('mention_type', models.CharField(choices=[('PERSON', 'Kişi'), ('LOCATION', 'Yer'), ('TIME', 'Zaman'), ('EVENT', 'Olay'), ('ORG', 'Kurum'), ('PRONOUN', 'Zamir')], max_length=16)),
                ('audio_start', models.FloatField(blank=True, null=True)),
                ('audio_end', models.FloatField(blank=True, null=True)),
                ('is_conflict', models.BooleanField(default=False)),
                ('conflict_reason', models.CharField(blank=True, choices=[('pronoun', 'Belirsiz zamir'), ('relative_time', 'Belirsiz zaman ifadesi'), ('ambiguous_verb', 'Belirsiz eylem öznesi'), ('unknown_referent', 'Tanımlanamayan gönderge')], default='', max_length=32)),
                ('conflict_hint', models.CharField(blank=True, default='', max_length=300)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_action', models.CharField(blank=True, choices=[('ASSIGNED', 'Assigned'), ('UNKNOWN', 'Unknown fallback'), ('IGNORED', 'Ignored'), ('AUTO', 'Auto-resolved')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='diary.node')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='diary.session')),
            ],
            options={
                'ordering': ['session', 'char_start'],
                'indexes': [models.Index(fields=['session', 'char_start'], name='diary_menti_session_22e478_idx'), models.Index(fields=['is_conflict', 'resolved'], name='diary_menti_is_conf_bba98a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('MENTIONED_WITH', 'İle birlikte anıldı'), ('HAPPENED_AT', 'Şurada gerçekleşti'), ('HAPPENED_ON', 'Şu tarihte'), ('ASSOCIATED_WITH', 'İle ilişkili')], max_length=32)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='diary.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='diary.node')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='diary.session')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'relation'], name='diary_edge_source__520314_idx'), models.Index(fields=['target', 'relation'], name='diary_edge_target__497a7d_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'relation', 'session'), name='unique_edge_per_session')],
            },
        ),
    ]
