# Generated by Django 6.0.4 on 2026-05-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_session_eventification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounteredEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERSON', 'Kişi'), ('LOCATION', 'Yer'), ('TIME', 'Zaman'), ('EVENT', 'Olay'), ('ORG', 'Kurum'), ('OTHER', 'Diğer')], max_length=16)),
                ('label', models.CharField(max_length=200)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'label'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'label'), name='unique_encountered_entity_kind_label')],
            },
        ),
    ]
