# Generated by Django 6.0.4 on 2026-05-25 21:48

import diary.encryption
from django.db import migrations


def encrypt_existing_entity_data(apps, schema_editor):
    EncounteredEntity = apps.get_model("diary", "EncounteredEntity")
    Mention = apps.get_model("diary", "Mention")
    Node = apps.get_model("diary", "Node")

    for entity in EncounteredEntity.objects.all().iterator():
        entity.save(update_fields=["label"])

    for mention in Mention.objects.all().iterator():
        mention.save(update_fields=["surface", "lemma", "conflict_hint"])

    for node in Node.objects.all().iterator():
        node.save(update_fields=["aliases", "notes", "time_value"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_session_eventification_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounteredentity',
            name='label',
            field=diary.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='mention',
            name='conflict_hint',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mention',
            name='lemma',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mention',
            name='surface',
            field=diary.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='node',
            name='aliases',
            field=diary.encryption.EncryptedJSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='node',
            name='notes',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='node',
            name='time_value',
            field=diary.encryption.EncryptedTextField(blank=True, default=''),
        ),
        migrations.RunPython(encrypt_existing_entity_data, noop_reverse),
    ]
