# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0008_session_mood_session_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="mood_source",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="session",
            name="tags_source",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
